projects:
  app:
    schemaPath: "schemas/app.graphql"
    extensions:
      endpoints:
        default: "${env:SERVER_ENDPOINT}"
  database:
    schemaPath: "schemas/database.graphql"
    includes: ["src/schema.graphql"]
    extensions:
      endpoints:
        default:
          url: "${env:GRAPHCOOL_ENDPOINT}"
          headers:
            Authorization: "Bearer ${env:GRAPHCOOL_APIKEY}"
